server:
  port: 3344

# application
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          username: *
          password: *
          uri: * # http
