server:
  port: 8001

spring:
  application:
    name: springCloud-provier-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.2.1:3306/spring_cloud_01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql

# mybatis
mybatis:
  # config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    # 输出 mybatis SQL 语句，调试时打开，上线关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: org.zjh.pojo

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.116:7001/eureka/, http://192.168.2.116:7002/eureka/, http://192.168.2.116:7003/eureka/
  instance:
    instance-id: spring-cloud-provider-dept8001 # 修改eureka上的默认描述信息!

# 完善监控信息
info:
  app.name: zjh spring cloud server provider
  company.name: org.zjh
  hello: qaq