server:
  port: 9527

# application name
spring:
  application:
    name: spring-cloud-zuul

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.116:7001/eureka/, http://192.168.2.116:7002/eureka/, http://192.168.2.116:7003/eureka/
  instance:
    instance-id: spring-cloud-zuul-9527 # 修改eureka上的默认描述信息!
    prefer-ip-address: true # 显示 IP 地址
info:
  app.name: zuul

# zuul
zuul:
  prefix: /zjh # 全局访问前缀
  ignored-services: spring-cloud-provier-dept # 不能再使用这个路径访问了，ignored :忽略。 "*" 隐藏全部的
#  ignored-services: "*" # 不能再使用这个路径访问了，ignored :忽略。 "*" 隐藏全部的
  routes:
    spring-cloud-provier-dept: /mydept/**

