server:
  port: 7002

eureka:
  instance:
    hostname: eurekaDS02 # eureka 服务端名称
  client:
    register-with-eureka: false # 是否向eureka注册中心注册自己
    fetch-registry: false # fetch-registry如果为false， 则表示自己为注册中心I
    service-url:
      # 单机
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群
      defaultZone: http://192.168.2.116:7001/eureka/, http://192.168.2.116}:7003/eureka/
