server:
  port: 80
eureka:
  client:
    register-with-eureka: false # 不向 Eureka 注册自己
    service-url:
      defaultZone: http://192.168.2.116:7001/eureka/, http://192.168.2.116:7002/eureka/, http://192.168.2.116:7003/eureka/
